name: Coveralls

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Assurez-vous de remplacer cela par la commande appropriée pour installer vos dépendances.

      - name: Run tests and generate coverage
        run: npm test -- --coverage  # Assurez-vous de remplacer cela par la commande appropriée pour exécuter vos tests et générer la couverture.

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
