name: Create Release Tag

on:
  push:
    branches:
      - main  # Vous pouvez adapter cette branche en fonction de votre configuration.

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Git Tag
      id: create_tag
      run: |
        # Récupère la dernière version et l'incrémente (par exemple, de 1.0.0 à 1.0.1)
        LATEST_TAG=$(git describe --tags --abbrev=0)
        IFS='.' read -ra VERSION_PARTS <<< "$LATEST_TAG"
        NEXT_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((${VERSION_PARTS[2]} + 1))"
        
        # Crée un tag pour la nouvelle version
        git tag -a "$NEXT_VERSION" -m "Release $NEXT_VERSION"
        git push origin "$NEXT_VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
