name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine version number
      id: version
      run: echo "::set-output name=VERSION::$(cat VERSION)" # Remplacez cela par votre propre logique pour obtenir le numéro de version

    - name: Create Tag
      id: create_tag
      run: git tag v${{ steps.version.outputs.VERSION }}

    - name: Push Tag
      run: git push origin v${{ steps.version.outputs.VERSION }}
      if: success()
